package com.example.lindroidcode.greendaoatoz.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lindroidcode.greendaoatoz.beans.AudioBean;
import com.example.lindroidcode.greendaoatoz.beans.UserBean;

import com.example.lindroidcode.greendaoatoz.entity.AudioBeanDao;
import com.example.lindroidcode.greendaoatoz.entity.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig audioBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final AudioBeanDao audioBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        audioBeanDaoConfig = daoConfigMap.get(AudioBeanDao.class).clone();
        audioBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        audioBeanDao = new AudioBeanDao(audioBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(AudioBean.class, audioBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        audioBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public AudioBeanDao getAudioBeanDao() {
        return audioBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
