/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_example_lindroidcode_nativerelated_LinNative
#define _Included_com_example_lindroidcode_nativerelated_LinNative

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_com_example_lindroidcode_nativerelated_LinNative_initJni(JNIEnv *, jclass);
JNIEXPORT jobjectArray JNICALL Java_com_example_lindroidcode_nativerelated_LinNative_fetchTwoDimensionalArray(JNIEnv *env,
                                                                                                      jclass clazz,jint size);
#ifdef __cplusplus
}
#endif
#endif
